### ISSUE TITLE
Bundling Bloat

### ISSUE THREAD

**Issue by shawnkelleydev** [voracious/vite-plugin-node-polyfills#14]
I was so excited to find this plugin!  This is my first issue ever on GitHub, so I'm sure I'm doing it wrong, but here we go:

While it seems to work, this plugin unfortunately also seems to break Vite's efficient bundling, as my bundles with this plugin seem to be 25% to 120% larger than their pre-plugin counterparts.

Is this expected / are others experiencing this?

**Comment by voracious** [comment]
Hi @shawnkelleydev. 👋 Congrats on your first issue! 🎉

The behavior you are describing makes sense to me. This package introduces polyfills for Node modules that would otherwise be ignored by Vite, which means extra code will be included in your project to provide (or stub) the behavior of the underlying module.

**Comment by voracious** [comment]
I'm going to close this, as I think the behavior is correct, but feel free to add more context if you still think some changes need to be made.
